git add basis/*.sml
git add translate/*.sml
git add ast/*.sml
git add ein/*.sml
git add ein/sources.cm
git add gen/ir/*.spec
git add high-ir/*.sml
git add high-opt/*.sml
git add high-to-mid/*.sml
git add high-to-mid/sources.cm
git add mid-ir/*.sml
git add options/ctl.sml
git add cxx-util/*.sml
git add driver/*.sml
git add simple/*.sml
git add simplify/*.sml
git add typechecker/*.sml